name: Lint code

on:
  - push
  - pull_request

jobs:
  build:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Python code quality and lint action
      uses: ricardochaves/python-lint@v1.3.0
      with:
        python-root-list: "charms"
        use-pylint: true
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: "max-line-length = 88"
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""