name: Functional test

on:
  - push
  - pull_request

jobs:
  func-test-metallb:
    runs-on: ubuntu-latest
    name: Setup infra
    steps:
    - name: Install MicroK8s with microk8s-action
      uses: balchua/microk8s-actions@v0.1.2
      with:
        channel: '1.18/stable'
        rbac: 'false'
        dns: 'true'
    
    - name: Additional MicroK8s setup
      run: |
        sudo microk8s.enable storage

    - name: Install Juju
      run: |
        sudo snap install juju --classic
        sudo juju bootstrap microk8s microk8s
    
    - name: Deploy MetalLB
      run: |
        juju add-model metallb-system
        juju status


