name: Functional test

on:
  - push
  - pull_request

jobs:
  func-test-metallb:
    runs-on: ubuntu-latest
    name: Functional test metallb
    timeout-minutes: 15
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo snap install juju --classic
        sudo snap install charmcraft --beta
        sudo apt-get install python3-setuptools
        pip3 install juju-wait

    - name: Build charms
      run: |
        charmcraft build --from charms/metallb-controller
        charmcraft build --from charms/metallb-speaker

    - name: Install MicroK8s with microk8s-action
      uses: balchua/microk8s-actions@v0.1.2
      with:
        channel: '1.18/stable'
        rbac: 'false'
        dns: 'true'
    
    - name: Additional MicroK8s setup
      run: |
        sudo microk8s.enable storage

    - name: Bootstrap MicroK8s with Juju
      run: |
        sudo juju bootstrap microk8s microk8s

    - name: Deploy MetalLB
      run: |
        sudo juju add-model metallb-system
        sudo juju deploy ./metallb-controller.charm
        sudo juju deploy ./metallb-speaker.charm
        sudo juju config metallb-controller iprange="10.152.183.240-10.152.183.250"
    
    - name: Wait for stable environment
      run: |
        sudo juju wait
        sudo juju status > juju-status-metallb.txt

    - name: Upload juju status to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: juju-status-metallb
        path: juju-status-metallb.txt

    - name: Check pods status
      run: |
        kubectl get pods -n metallb-system

    - name: Deploy microbot
      run: |
        sudo juju deploy ./docs/example-microbot-lb.yaml
        sudo juju wait
      
    - name: Check availability of service
      run: |
        kubectl get all

