name: Extra func test with RBAC enabled

on:
  - pull_request

jobs:
  func-test-metallb:
    runs-on: ubuntu-latest
    name: Functional test with RBAC enabled
    timeout-minutes: 10
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo snap install juju --classic
        sudo snap install charmcraft --beta
        sudo snap install juju-wait --classic
    
    - name: Create tmp dir for artifacts
      run: mkdir -p tmp

    - name: Build charms
      run: |
        charmcraft build --from charms/metallb-controller
        charmcraft build --from charms/metallb-speaker

    - name: Install MicroK8s with microk8s-action
      uses: balchua/microk8s-actions@v0.1.3
      with:
        channel: '1.18/stable'
        rbac: 'true'
        dns: 'true'
        storage: 'true'

    - name: Wait 10s for MicroK8s to be ready
      run: sleep 10

    - name: Bootstrap MicroK8s with Juju
      run: |
        sudo juju bootstrap microk8s microk8s
    
    - name: Deploy MetalLB
      run: |
        sudo juju add-model metallb-system
        sudo juju deploy ./metallb-controller.charm --resource metallb-controller-image='metallb/controller:v0.9.3'
        sudo juju deploy ./metallb-speaker.charm --resource metallb-speaker-image='metallb/speaker:v0.9.3'
        sudo juju config metallb-controller iprange="10.1.240.241-10.1.240.242"
    
    - name: Wait for stable environment
      run: |
        sudo /snap/bin/juju-wait

    - name: Confirm failure without RBAC rules
      run: |
        sudo juju status 2>&1 | tee tmp/juju-status-metallb-1.txt
        if [[ $(sudo juju status | grep 'error\|blocked') ]];
        then echo "Deployment failed as expected.";
        else exit 1;
        fi

    - name: Apply RBAC rules for operator pods
      run: sudo microk8s.kubectl apply -f docs/rbac-permissions-controller.yaml

    - name: Resolve units in error
      run: |
        if [[ $(sudo juju status metallb-controller | grep 'error') ]];
        then sudo juju resolve metallb-controller/0; fi
        if [[ $(sudo juju status metallb-speaker | grep 'error') ]];
        then sudo juju resolve metallb-speaker/0; fi
    
    - name: Wait for stable environment
      run: |
        sudo /snap/bin/juju-wait

    - name: Check for errors in juju status
      run: |  
        sudo juju status 2>&1 | tee tmp/juju-status-metallb-2.txt
        if [[ $(sudo juju status | grep 'error\|blocked') ]];
        then exit 1;
        else echo "No errors or blocked status detected.";
        fi

    - name: Check pods status
      run: sudo kubectl get pods -n metallb-system 2>&1 | tee tmp/metallb-pods.txt

    - name: Deploy microbot
      run: kubectl apply -f ./docs/example-microbot-lb.yaml
      
    - name: Check availability of microbot service
      run: |
        kubectl get all 2>&1 | tee tmp/microbot-status.txt

    - name: Curl service on microbot external ip
      run: |
         if curl --fail --connect-timeout 10 `kubectl get service/microbot-lb \
         --no-headers | awk '{print$4}'`; then echo "curl successfull";
         else exit 1;
         fi      

    - name: Upload Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-run-artifacts
        path: tmp
